on:
  push:
    branches:
    - main

name: Build and Deploy to Cloud Run
env:
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT }}/bcalc-pwa:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t ${{ env.IMAGE_NAME }} .
        docker push ${{ env.IMAGE_NAME }}
        
    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy ${{ secrets.GCP_SERVICE }} \
          --region ${{ secrets.GCP_REGION }} \
          --image ${{ env.IMAGE_NAME }} \
          --platform "managed" \
          --allow-unauthenticated \
          --quiet 
